root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ./cmd/server/main.go"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "tests/e2e"]
include_ext = ["go", "tpl", "html", "yaml"]

[screen]
clear_on_rebuild = true
